### ISSUE TITLE
improve install instruction

### ISSUE THREAD

**Issue by PicoGhost** [gregsadetsky/wfmu-rp2040-pimoroni-radio#1]
To make it easier for other user., in the install instruction (at the end of `readme.md`), I suggest to add:

Copy (overwrite) the files (`AudioFileSourceHTTPStream.*`, `AudioFileSourceICYStream.*`) from this repo to Arduino library (by default `~/Arduino/libraries/ESP8266Audio/src/`)

then it compile without issue.
BTW: @gregsadetsky thanks a lot ! :+1:

**Comment by gregsadetsky** [comment]
hey thanks for the suggestion!

just for context, I didn't want to override the original library files in case they'd come in handy (for example, if you wanted to use the original library with a different board than the rp2040)

but overriding those files could also make sense if you wanted other (existing) ESP8266Audio examples to work for sure. I'll add a note in the readme like you suggested

just out of curiosity, are you using an rp2040 and streaming internet radio using this code? always interested to hear about use cases! cheers

**Comment by PicoGhost** [comment]
I use this code for a webradio build with a Pico W +Pimoroni PicoAudio. I improved a bit the code using the internal LED:  flashing  when connecting to wifi, and always on while connected. Handy for troubleshooting. I am still having issue with dropping frame (not sure if this is the rigrh word). Need to investigate, internet speed, electrical connection between pi and hat. From your side, are you happy with sound quality?

**Comment by gregsadetsky** [comment]
ah super good idea re: LED to show connecting vs connected!

ah yeah, I do sometimes have issues with audio frames being dropped -- this is why I so aggressively added a "reboot" [here](https://github.com/gregsadetsky/wfmu-rp2040-pimoroni-radio/blob/main/StreamMP3FromHTTP.ino#L117) whenever the audio buffer is empty... not the best solution at all, but at least the device will automatically recover

one thing you could try is playing with the value [here](https://github.com/gregsadetsky/wfmu-rp2040-pimoroni-radio/blob/main/StreamMP3FromHTTP.ino#L93) i.e. the AudioFileSourceBuffer size try to make it smaller - does that make frame dropouts worse? and then try to make it larger - does that change/improve things?

I'd say that sound quality on my side is pretty good yeah. has that been a problem on your side?

also, I forgot to add, but I did follow your suggestion and added some instructions to the project's readme -- see [here](https://github.com/gregsadetsky/wfmu-rp2040-pimoroni-radio?tab=readme-ov-file#extra-note-re-compilingusing-for-other-projects). thanks a lot!
